# Generated by Django 3.1.2 on 2021-04-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='project_id',
            field=models.IntegerField(db_index=True, verbose_name='project_id'),
        ),
    ]
