# Generated by Django 3.1.2 on 2021-04-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_auto_20210411_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
