# Generated by Django 3.1.2 on 2021-06-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0005_task_tasktestcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0, verbose_name='任务id')),
            ],
        ),
    ]
