# Generated by Django 3.1.2 on 2021-06-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0006_runtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.IntegerField(default=None, null=True, verbose_name='days'),
        ),
        migrations.AddField(
            model_name='task',
            name='hour',
            field=models.IntegerField(default=None, null=True, verbose_name='hour'),
        ),
        migrations.AddField(
            model_name='task',
            name='interval_switch',
            field=models.BooleanField(default=False, verbose_name='interval_switch'),
        ),
        migrations.AddField(
            model_name='task',
            name='minutes',
            field=models.IntegerField(default=None, null=True, verbose_name='minutes'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='start_time'),
        ),
    ]
