# Generated by Django 3.1.2 on 2021-06-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0007_auto_20210620_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='days',
            field=models.IntegerField(default=0, null=True, verbose_name='days'),
        ),
        migrations.AlterField(
            model_name='task',
            name='hour',
            field=models.IntegerField(default=0, null=True, verbose_name='hour'),
        ),
        migrations.AlterField(
            model_name='task',
            name='minutes',
            field=models.IntegerField(default=0, null=True, verbose_name='minutes'),
        ),
    ]
