# Generated by Django 3.1.2 on 2021-06-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0008_auto_20210620_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='hour',
            new_name='hours',
        ),
    ]
